name: untitled
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  path_provider: ^2.1.1
  shared_preferences: ^2.2.3
  provider: ^6.1.1
  http: ^1.1.0
  just_audio: ^0.9.36
  audio_session: ^0.1.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Uthmanic
      fonts:
        - asset: assets/fonts/UthmanicHafs.ttf
  assets:
    - assets/pages/
    - assets/surah.json
    - assets/markers.json