name: quran_by_helal
description: "Quran by Helal - A beautiful Quran reader app with audio recitation and bookmarking features."
publish_to: 'none'

version: 1.1.4+5

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  http: ^1.2.2
  just_audio: ^0.9.46
  audio_session: ^0.1.25
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.2.5
  connectivity_plus: ^5.0.2
  path_provider: ^2.1.2
  dio: ^5.4.0
  crypto: ^3.0.3
  flutter_secure_storage: ^9.0.0
  wakelock_plus: ^1.2.9
  audio_service: ^0.18.18
  firebase_core: ^2.24.2
  firebase_analytics: ^10.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  # App icon configuration
  # Note: You'll need to add app icons in android/app/src/main/res/ and ios/Runner/Assets.xcassets/
  
  # fonts:
    # - family: Uthmanic
    #   fonts:
    #     - asset: assets/fonts/UthmanicHafs.ttf
  
  assets:
    - assets/pages/
    - assets/surah.json
    - assets/markers.json
    - assets/app_icon.png
