name: quran_reader
description: "A beautiful Quran reader app with audio recitation and bookmarking features."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  http: ^1.2.2
  just_audio: ^0.9.46
  audio_session: ^0.1.25
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # App icon configuration
  # Note: You'll need to add app icons in android/app/src/main/res/ and ios/Runner/Assets.xcassets/
  
  fonts:
    - family: Uthmanic
      fonts:
        - asset: assets/fonts/UthmanicHafs.ttf
  
  assets:
    - assets/pages/
    - assets/surah.json
    - assets/markers.json
    # Add assets/images/ folder when you have app icons to include